import type { Context } from "tentacular";

interface PrioritizedDigest {
  digestMarkdown: string;
  criticalCount: number;
  highCount: number;
  mediumCount: number;
  lowCount: number;
  totalNew: number;
  topItems: { repo: string; package: string; severity: string; summary: string }[];
}

interface NotifyOutput {
  delivered: boolean;
  status: number;
}

/** Post the formatted security digest to Slack via webhook */
export default async function run(ctx: Context, input: unknown): Promise<NotifyOutput> {
  const digest = input as PrioritizedDigest;

  const slack = ctx.dependency("slack-webhook");
  if (!slack.secret) {
    ctx.log.warn("No slack webhook, skipping notification");
    return { delivered: false, status: 0 };
  }

  if (digest.totalNew === 0) {
    ctx.log.info("No new alerts, skipping Slack notification");
    return { delivered: true, status: 200 };
  }

  const severityLine = [
    digest.criticalCount > 0 ? `:rotating_light: Critical: *${digest.criticalCount}*` : null,
    digest.highCount > 0 ? `:warning: High: *${digest.highCount}*` : null,
    digest.mediumCount > 0 ? `:large_yellow_circle: Medium: *${digest.mediumCount}*` : null,
    digest.lowCount > 0 ? `:white_circle: Low: *${digest.lowCount}*` : null,
  ].filter(Boolean).join("  |  ");

  const topItemsText = digest.topItems.length > 0
    ? digest.topItems
        .map((item) => `  - *${item.repo}*: \`${item.package}\` (${item.severity}) - ${item.summary}`)
        .join("\n")
    : "  None";

  const blocks: Record<string, unknown>[] = [
    {
      type: "header",
      text: { type: "plain_text", text: `Security Digest: ${digest.totalNew} New Alerts` },
    },
    {
      type: "section",
      text: {
        type: "mrkdwn",
        text: severityLine,
      },
    },
    {
      type: "section",
      text: {
        type: "mrkdwn",
        text: `*Top Priority Items:*\n${topItemsText}`,
      },
    },
    {
      type: "section",
      text: {
        type: "mrkdwn",
        text: digest.digestMarkdown.length > 2900
          ? digest.digestMarkdown.substring(0, 2900) + "\n_...truncated_"
          : digest.digestMarkdown,
      },
    },
    { type: "divider" },
    {
      type: "context",
      elements: [
        { type: "mrkdwn", text: `Generated by Tentacular GitHub Security Digest | ${new Date().toISOString()}` },
      ],
    },
  ];

  ctx.log.info("Sending security digest to Slack");

  const webhookUrl = new URL(slack.secret);
  const res = await slack.fetch!(webhookUrl.pathname, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ blocks }),
  });

  ctx.log.info(`Slack response: ${res.status}`);
  return { delivered: res.ok, status: res.status };
}
