import type { Context } from "tentacular";
import { Client } from "jsr:@db/postgres@0.19.5";
import type { ScoreOutput, ScoredLead } from "./score-leads.ts";

interface RouteResult {
  stored: number;
  highScoreAlerts: number;
  lowScoreLogged: number;
  sheetUpdated: boolean;
  slackDelivered: boolean;
}

const CREATE_TABLE = `
CREATE TABLE IF NOT EXISTS enriched_leads (
  id SERIAL PRIMARY KEY,
  row_number INT NOT NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  company TEXT NOT NULL,
  score INT NOT NULL,
  explanation TEXT NOT NULL DEFAULT '',
  icp_fit TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_enriched_leads_score
  ON enriched_leads (score DESC);
CREATE INDEX IF NOT EXISTS idx_enriched_leads_created
  ON enriched_leads (created_at DESC);
`;

const INSERT_LEAD = `
INSERT INTO enriched_leads (row_number, name, email, company, score, explanation, icp_fit)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id;
`;

/** Store enriched leads in Postgres, update Google Sheet, route by score to Slack */
export default async function run(ctx: Context, input: unknown): Promise<RouteResult> {
  const { scoredLeads } = input as ScoreOutput;

  if (scoredLeads.length === 0) {
    ctx.log.info("No leads to store or route");
    return { stored: 0, highScoreAlerts: 0, lowScoreLogged: 0, sheetUpdated: false, slackDelivered: false };
  }

  let stored = 0;
  let sheetUpdated = false;
  let slackDelivered = false;

  const highScore = scoredLeads.filter((l) => l.score >= 70);
  const lowScore = scoredLeads.filter((l) => l.score < 70);

  // Store in Postgres
  const pg = ctx.dependency("tentacular-postgres");
  if (pg.secret) {
    const client = new Client({
      hostname: pg.host,
      port: pg.port,
      database: pg.database,
      user: pg.user,
      password: pg.secret,
      tls: { enabled: false },
    });

    try {
      await client.connect();
      await client.queryArray(CREATE_TABLE);

      for (const sl of scoredLeads) {
        await client.queryArray(INSERT_LEAD, [
          sl.lead.rowNumber,
          sl.lead.name,
          sl.lead.email,
          sl.lead.company,
          sl.score,
          sl.explanation,
          sl.icp_fit_details,
        ]);
        stored++;
      }

      ctx.log.info(`Stored ${stored} leads in Postgres`);
    } finally {
      await client.end();
    }
  } else {
    ctx.log.warn("No postgres credentials, skipping database storage");
  }

  // Update Google Sheet with scores
  const sheets = ctx.dependency("google-sheets");
  const sheetsId = ctx.config.sheets_id as string;
  if (sheets.secret && sheetsId) {
    const sheetName = (ctx.config.sheet_name as string) ?? "Leads";

    try {
      // Write scores to column E (Score) and F (Explanation)
      const updateData: { range: string; values: string[][] }[] = scoredLeads.map((sl) => ({
        range: `${sheetName}!E${sl.lead.rowNumber}:F${sl.lead.rowNumber}`,
        values: [[String(sl.score), sl.explanation]],
      }));

      const res = await sheets.fetch!(
        `/v4/spreadsheets/${sheetsId}/values:batchUpdate`,
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            valueInputOption: "RAW",
            data: updateData,
          }),
        },
      );

      sheetUpdated = res.ok;
      if (!res.ok) {
        ctx.log.warn(`Sheet update failed: ${res.status}`);
      } else {
        ctx.log.info(`Updated ${scoredLeads.length} rows in Google Sheet`);
      }
    } catch (err) {
      ctx.log.warn(`Sheet update error: ${err instanceof Error ? err.message : String(err)}`);
    }
  }

  // Slack alert for high-score leads
  const slack = ctx.dependency("slack-webhook");
  if (slack.secret && highScore.length > 0) {
    const leadLines = highScore
      .map((sl) => `  - *${sl.lead.name}* (${sl.lead.company}) - Score: *${sl.score}* - ${sl.explanation}`)
      .join("\n");

    const blocks: Record<string, unknown>[] = [
      {
        type: "header",
        text: { type: "plain_text", text: `${highScore.length} High-Score Lead(s) Detected` },
      },
      {
        type: "section",
        text: {
          type: "mrkdwn",
          text: `*ICP-matched leads (score >= 70):*\n${leadLines}`,
        },
      },
      {
        type: "context",
        elements: [
          { type: "mrkdwn", text: `${lowScore.length} low-score lead(s) logged for batch review | Generated by Tentacular | ${new Date().toISOString()}` },
        ],
      },
    ];

    const webhookUrl = new URL(slack.secret);
    const slackRes = await slack.fetch!(webhookUrl.pathname, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ blocks }),
    });

    slackDelivered = slackRes.ok;
    ctx.log.info(`Slack notification: ${slackRes.status}`);
  }

  return {
    stored,
    highScoreAlerts: highScore.length,
    lowScoreLogged: lowScore.length,
    sheetUpdated,
    slackDelivered,
  };
}
