import type { Context } from "tentacular";

interface TestCase {
  name: string;
  passed: boolean;
  latency_ms: number;
  error?: string;
}

interface CollectedResults {
  services: Array<{
    service: string;
    passed: boolean;
    tests: TestCase[];
  }>;
  totalTests: number;
  totalPassed: number;
  overallPassed: boolean;
  collectedAt?: string;
}

interface RenderResult {
  s3Path: string;
  stored: boolean;
  results?: CollectedResults;
}

/** Generate an HTML test report with pass/fail badges and latency details, store in RustFS */
export default async function run(ctx: Context, input: unknown): Promise<RenderResult> {
  const data = input as CollectedResults;

  // Store in RustFS
  const rustfs = ctx.dependency("tentacular-rustfs");
  let s3Path = "";
  let stored = false;

  if (!rustfs.secret) {
    ctx.log.warn("No RustFS credentials, skipping report storage");
    return { s3Path, stored };
  }

  const collectedAt = data.collectedAt ?? new Date().toISOString();
  const dateStr = collectedAt.split("T")[0];
  const html = generateHtml({ ...data, collectedAt });

  s3Path = `/tentacular/reports/exo-test/${dateStr}/report-${Date.now()}.html`;
  try {
    const res = await rustfs.fetch!(s3Path, {
      method: "PUT",
      headers: { "Content-Type": "text/html; charset=utf-8" },
      body: html,
    });
    stored = res.ok;
    if (res.ok) {
      ctx.log.info(`Stored test report at ${s3Path}`);
    } else {
      ctx.log.warn(`RustFS PUT failed: ${res.status}`);
    }
  } catch (err) {
    ctx.log.warn(`Failed to store report: ${err instanceof Error ? err.message : String(err)}`);
  }

  return { s3Path, stored, results: data };
}

/** Generate HTML test report */
function generateHtml(data: CollectedResults): string {
  const overallBadge = data.overallPassed
    ? '<span style="background:#28a745;color:white;padding:4px 12px;border-radius:4px;font-weight:bold">PASS</span>'
    : '<span style="background:#dc3545;color:white;padding:4px 12px;border-radius:4px;font-weight:bold">FAIL</span>';

  const serviceRows = data.services.map((svc) => {
    const badge = svc.passed
      ? '<span style="color:#28a745;font-weight:bold">PASS</span>'
      : '<span style="color:#dc3545;font-weight:bold">FAIL</span>';

    const testRows = svc.tests.map((t) => {
      const icon = t.passed ? "&#10004;" : "&#10008;";
      const color = t.passed ? "#28a745" : "#dc3545";
      const errorCell = t.error ? `<td style="color:#dc3545">${escapeHtml(t.error)}</td>` : "<td>-</td>";
      return `<tr><td style="color:${color}">${icon}</td><td>${escapeHtml(t.name)}</td><td>${t.latency_ms}ms</td>${errorCell}</tr>`;
    }).join("\n");

    const avgLatency = svc.tests.length > 0
      ? Math.round(svc.tests.reduce((sum, t) => sum + t.latency_ms, 0) / svc.tests.length)
      : 0;

    return `
      <div class="service">
        <h3>${escapeHtml(svc.service)} ${badge} <span class="latency">(avg: ${avgLatency}ms)</span></h3>
        <table>
          <thead><tr><th></th><th>Test</th><th>Latency</th><th>Error</th></tr></thead>
          <tbody>${testRows}</tbody>
        </table>
      </div>`;
  }).join("\n");

  return `<!DOCTYPE html>
<html>
<head>
  <title>Exoskeleton Smoke Test Report - ${data.collectedAt}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 900px; margin: 0 auto; padding: 20px; }
    .header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px; }
    .summary { background: #f8f9fa; padding: 16px; border-radius: 8px; margin: 16px 0; }
    .service { margin: 20px 0; }
    .latency { color: #6c757d; font-size: 0.85em; font-weight: normal; }
    table { width: 100%; border-collapse: collapse; margin: 8px 0; }
    th, td { padding: 6px 12px; border: 1px solid #dee2e6; text-align: left; }
    th { background: #f8f9fa; }
  </style>
</head>
<body>
  <div class="header">
    <h1>Exoskeleton Smoke Test</h1>
    ${overallBadge}
  </div>
  <div class="summary">
    <p><strong>Date:</strong> ${data.collectedAt}</p>
    <p><strong>Tests:</strong> ${data.totalPassed}/${data.totalTests} passed</p>
    <p><strong>Services:</strong> ${data.services.map((s) => `${s.service} (${s.passed ? "OK" : "FAIL"})`).join(", ")}</p>
  </div>
  ${serviceRows}
  <footer><p style="color:#6c757d;margin-top:40px">Generated by Tentacular E2E Exoskeleton Test</p></footer>
</body>
</html>`;
}

/** Escape HTML entities */
function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
