import type { Context } from "tentacular";
import { Client } from "jsr:@db/postgres@0.19.5";
import type { ResponseOutline } from "./generate-outline.ts";

interface StoreResult {
  stored: boolean;
  rustfsPath: string;
  rowId: number;
  slackDelivered: boolean;
}

const CREATE_TABLE = `
CREATE TABLE IF NOT EXISTS content_research (
  id SERIAL PRIMARY KEY,
  target_url TEXT NOT NULL,
  title TEXT NOT NULL,
  contrarian_angle TEXT NOT NULL,
  outline_json JSONB NOT NULL,
  rustfs_path TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_content_research_created
  ON content_research (created_at DESC);
`;

const INSERT = `
INSERT INTO content_research (target_url, title, contrarian_angle, outline_json, rustfs_path)
VALUES ($1, $2, $3, $4, $5)
RETURNING id;
`;

/** Store research + outline in RustFS and Postgres, then notify via Slack */
export default async function run(ctx: Context, input: unknown): Promise<StoreResult> {
  const outline = input as ResponseOutline;
  const targetUrl = ctx.config.target_url as string;
  const now = new Date().toISOString();
  const datePath = now.substring(0, 10);

  let rustfsPath = "";
  let rowId = 0;
  let slackDelivered = false;

  // Store in RustFS
  const rustfs = ctx.dependency("tentacular-rustfs");
  if (rustfs.secret) {
    const key = `content-research/${datePath}/${Date.now()}-outline.json`;
    const payload = JSON.stringify({ targetUrl, outline, generatedAt: now }, null, 2);

    ctx.log.info(`Uploading research to RustFS: ${key}`);

    const putRes = await rustfs.fetch!(`/content-research/${key}`, {
      method: "PUT",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${rustfs.secret}`,
      },
      body: payload,
    });

    if (putRes.ok) {
      rustfsPath = key;
      ctx.log.info(`Stored in RustFS: ${key}`);
    } else {
      ctx.log.warn(`RustFS upload failed: ${putRes.status} ${putRes.statusText}`);
    }
  } else {
    ctx.log.warn("No rustfs credentials, skipping S3 storage");
  }

  // Store metadata in Postgres
  const pg = ctx.dependency("tentacular-postgres");
  if (pg.secret) {
    const client = new Client({
      hostname: pg.host,
      port: pg.port,
      database: pg.database,
      user: pg.user,
      password: pg.secret,
      tls: { enabled: false },
    });

    try {
      await client.connect();
      await client.queryArray(CREATE_TABLE);

      const result = await client.queryArray(INSERT, [
        targetUrl,
        outline.titleOptions[0] ?? "Untitled",
        outline.contrarian_hook,
        JSON.stringify(outline),
        rustfsPath,
      ]);

      rowId = Number(result.rows[0]?.[0] ?? 0);
      ctx.log.info(`Stored metadata as row ${rowId}`);
    } finally {
      await client.end();
    }
  } else {
    ctx.log.warn("No postgres credentials, skipping database storage");
  }

  // Notify via Slack
  const slack = ctx.dependency("slack-webhook");
  if (slack.secret) {
    const sectionsList = outline.sections
      .map((s) => `  - *${s.heading}*: ${s.keyPoints[0] ?? ""}`)
      .join("\n");

    const blocks: Record<string, unknown>[] = [
      {
        type: "header",
        text: { type: "plain_text", text: "Content Research Complete" },
      },
      {
        type: "section",
        text: {
          type: "mrkdwn",
          text: `*Target:* <${targetUrl}|${targetUrl}>\n*Hook:* ${outline.contrarian_hook}`,
        },
      },
      {
        type: "section",
        text: {
          type: "mrkdwn",
          text: `*Title Options:*\n${outline.titleOptions.map((t) => `  - ${t}`).join("\n")}`,
        },
      },
      {
        type: "section",
        text: {
          type: "mrkdwn",
          text: `*Sections:*\n${sectionsList}`,
        },
      },
      {
        type: "context",
        elements: [
          { type: "mrkdwn", text: `~${outline.estimated_word_count} words | Generated by Tentacular | ${now}` },
        ],
      },
    ];

    const webhookUrl = new URL(slack.secret);
    const slackRes = await slack.fetch!(webhookUrl.pathname, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ blocks }),
    });

    slackDelivered = slackRes.ok;
    ctx.log.info(`Slack notification: ${slackRes.status}`);
  } else {
    ctx.log.warn("No slack webhook, skipping notification");
  }

  return { stored: rowId > 0 || rustfsPath !== "", rustfsPath, rowId, slackDelivered };
}
