import type { Context } from "tentacular";
import { Client } from "jsr:@db/postgres@0.19.5";
import type { RiskReport } from "./synthesize-report.ts";

interface StoreResult {
  stored: boolean;
  rowId: number;
  htmlPath: string;
  slackDelivered: boolean;
}

const CREATE_TABLE = `
CREATE TABLE IF NOT EXISTS contract_reviews (
  id SERIAL PRIMARY KEY,
  risk_score INT NOT NULL,
  critical_count INT NOT NULL DEFAULT 0,
  summary TEXT NOT NULL DEFAULT '',
  report_json JSONB NOT NULL,
  rustfs_html_path TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_contract_reviews_score
  ON contract_reviews (risk_score DESC);
CREATE INDEX IF NOT EXISTS idx_contract_reviews_created
  ON contract_reviews (created_at DESC);
`;

const INSERT = `
INSERT INTO contract_reviews (risk_score, critical_count, summary, report_json, rustfs_html_path)
VALUES ($1, $2, $3, $4, $5)
RETURNING id;
`;

/** Store risk report in Postgres, render HTML to RustFS, and post summary to Slack */
export default async function run(ctx: Context, input: unknown): Promise<StoreResult> {
  const report = input as RiskReport;
  const now = new Date().toISOString();
  const datePath = now.substring(0, 10);

  let rowId = 0;
  let htmlPath = "";
  let slackDelivered = false;

  // Render HTML report
  const html = renderHtml(report, now);

  // Store HTML in RustFS
  const rustfs = ctx.dependency("tentacular-rustfs");
  if (rustfs.secret) {
    const key = `contract-reviews/${datePath}/${Date.now()}-report.html`;

    const putRes = await rustfs.fetch!(`/contract-reviews/${key}`, {
      method: "PUT",
      headers: {
        "Content-Type": "text/html",
        "Authorization": `Bearer ${rustfs.secret}`,
      },
      body: html,
    });

    if (putRes.ok) {
      htmlPath = key;
      ctx.log.info(`Stored HTML report in RustFS: ${key}`);
    } else {
      ctx.log.warn(`RustFS upload failed: ${putRes.status}`);
    }
  }

  // Store in Postgres
  const pg = ctx.dependency("tentacular-postgres");
  if (pg.secret) {
    const client = new Client({
      hostname: pg.host,
      port: pg.port,
      database: pg.database,
      user: pg.user,
      password: pg.secret,
      tls: { enabled: false },
    });

    try {
      await client.connect();
      await client.queryArray(CREATE_TABLE);

      const result = await client.queryArray(INSERT, [
        report.overallRiskScore,
        report.criticalFindings.length,
        report.summary,
        JSON.stringify(report),
        htmlPath,
      ]);

      rowId = Number(result.rows[0]?.[0] ?? 0);
      ctx.log.info(`Stored review as row ${rowId}`);
    } finally {
      await client.end();
    }
  }

  // Notify Slack
  const slack = ctx.dependency("slack-webhook");
  if (slack.secret) {
    const riskEmoji = report.overallRiskScore >= 7 ? ":rotating_light:" :
                      report.overallRiskScore >= 4 ? ":warning:" : ":white_check_mark:";

    const criticalList = report.criticalFindings.length > 0
      ? report.criticalFindings.map((f) => `  - ${f}`).join("\n")
      : "  None";

    const blocks: Record<string, unknown>[] = [
      {
        type: "header",
        text: { type: "plain_text", text: "Contract Review Complete" },
      },
      {
        type: "section",
        text: {
          type: "mrkdwn",
          text: `${riskEmoji} *Overall Risk Score: ${report.overallRiskScore}/10*`,
        },
      },
      {
        type: "section",
        text: {
          type: "mrkdwn",
          text: `*Critical Findings (${report.criticalFindings.length}):*\n${criticalList}`,
        },
      },
      {
        type: "section",
        text: {
          type: "mrkdwn",
          text: report.summary.length > 2900
            ? report.summary.substring(0, 2900) + "\n_...truncated_"
            : report.summary,
        },
      },
      {
        type: "context",
        elements: [
          { type: "mrkdwn", text: `Generated by Tentacular Contract Clause Reviewer | ${now}` },
        ],
      },
    ];

    const webhookUrl = new URL(slack.secret);
    const slackRes = await slack.fetch!(webhookUrl.pathname, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ blocks }),
    });

    slackDelivered = slackRes.ok;
    ctx.log.info(`Slack notification: ${slackRes.status}`);
  }

  return { stored: rowId > 0, rowId, htmlPath, slackDelivered };
}

/** Render the risk report as a simple HTML document */
function renderHtml(report: RiskReport, timestamp: string): string {
  const riskColor = report.overallRiskScore >= 7 ? "#dc3545" :
                    report.overallRiskScore >= 4 ? "#ffc107" : "#28a745";

  const criticalHtml = report.criticalFindings.length > 0
    ? report.criticalFindings.map((f) => `<li>${escapeHtml(f)}</li>`).join("\n")
    : "<li>None</li>";

  const negotiationHtml = report.negotiationPoints.length > 0
    ? report.negotiationPoints.map((p) => `<li>${escapeHtml(p)}</li>`).join("\n")
    : "<li>None</li>";

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Contract Risk Report - ${timestamp}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }
    .risk-score { font-size: 48px; font-weight: bold; color: ${riskColor}; }
    h1, h2 { color: #333; }
    ul { line-height: 1.6; }
    .summary { background: #f8f9fa; padding: 16px; border-radius: 8px; margin: 16px 0; }
    .footer { color: #666; font-size: 12px; margin-top: 40px; border-top: 1px solid #eee; padding-top: 10px; }
  </style>
</head>
<body>
  <h1>Contract Risk Report</h1>
  <p class="risk-score">${report.overallRiskScore}/10</p>

  <div class="summary">
    <p>${escapeHtml(report.summary)}</p>
  </div>

  <h2>Critical Findings</h2>
  <ul>${criticalHtml}</ul>

  <h2>Negotiation Points</h2>
  <ul>${negotiationHtml}</ul>

  <div class="footer">
    <p>Generated by Tentacular Contract Clause Reviewer | ${timestamp}</p>
  </div>
</body>
</html>`;
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
