import type { Context } from "tentacular";

interface ChangeSummary {
  url: string;
  summary: string;
  changedAt: string;
}

interface SummarizeOutput {
  summaries: ChangeSummary[];
  totalChanged: number;
}

interface NotifyOutput {
  delivered: boolean;
  status: number;
}

/** Post change summaries to Slack */
export default async function run(ctx: Context, input: unknown): Promise<NotifyOutput> {
  const data = input as SummarizeOutput;

  const slack = ctx.dependency("slack-webhook");
  if (!slack.secret) {
    ctx.log.warn("No slack webhook, skipping notification");
    return { delivered: false, status: 0 };
  }

  if (data.totalChanged === 0) {
    ctx.log.info("No changes detected, skipping Slack notification");
    return { delivered: true, status: 200 };
  }

  const changeBlocks: Record<string, unknown>[] = data.summaries.map((change) => ({
    type: "section",
    text: {
      type: "mrkdwn",
      text: `:eyes: *<${change.url}|${new URL(change.url).hostname}>*\n${change.summary}`,
    },
  }));

  const blocks: Record<string, unknown>[] = [
    {
      type: "header",
      text: { type: "plain_text", text: `Site Changes Detected: ${data.totalChanged} page(s)` },
    },
    ...changeBlocks,
    { type: "divider" },
    {
      type: "context",
      elements: [
        { type: "mrkdwn", text: `Generated by Tentacular Site Change Detector | ${new Date().toISOString()}` },
      ],
    },
  ];

  ctx.log.info("Sending change detection digest to Slack");

  const webhookUrl = new URL(slack.secret);
  const res = await slack.fetch!(webhookUrl.pathname, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ blocks }),
  });

  ctx.log.info(`Slack response: ${res.status}`);
  return { delivered: res.ok, status: res.status };
}
