import type { Context } from "tentacular";

interface EndpointStats {
  url: string;
  totalProbes: number;
  healthyProbes: number;
  uptimePct: number;
  p50LatencyMs: number;
  p95LatencyMs: number;
  p99LatencyMs: number;
  errorCount: number;
  minTlsExpiryDays: number | null;
  avgResponseTimeMs: number;
}

interface AggregateResult {
  endpoints: EndpointStats[];
  periodStart: string;
  periodEnd: string;
  overallUptimePct: number;
}

interface ReportOutput {
  html: string;
  summary: string;
  overallUptimePct: number;
  periodStart: string;
  periodEnd: string;
}

const LLM_PROMPT = `You are an SRE analyst generating a weekly uptime report. Analyze the provided endpoint statistics and produce:

1. A narrative summary (2-3 paragraphs) highlighting:
   - Overall uptime trends
   - Any regressions or degradations
   - TLS certificate warnings (expiring within 30 days)
   - Latency outliers (p95 > 1000ms)
2. Key recommendations

Return a JSON object:
{
  "narrative": "<markdown formatted summary>",
  "recommendations": ["<rec1>", "<rec2>", ...]
}

Respond with valid JSON only, no markdown fences.`;

function buildStatsTable(endpoints: EndpointStats[]): string {
  const rows = endpoints.map((e) => {
    const tlsWarning = e.minTlsExpiryDays !== null && e.minTlsExpiryDays >= 0 && e.minTlsExpiryDays < 30
      ? ` <span style="color:orange">TLS expires in ${e.minTlsExpiryDays}d</span>` : "";
    const uptimeColor = e.uptimePct >= 99.9 ? "green" : e.uptimePct >= 99 ? "orange" : "red";
    return `<tr>
      <td>${e.url}</td>
      <td style="color:${uptimeColor}">${e.uptimePct}%</td>
      <td>${e.p50LatencyMs}ms</td>
      <td>${e.p95LatencyMs}ms</td>
      <td>${e.p99LatencyMs}ms</td>
      <td>${e.errorCount}</td>
      <td>${e.minTlsExpiryDays !== null && e.minTlsExpiryDays >= 0 ? e.minTlsExpiryDays + "d" : "N/A"}${tlsWarning}</td>
    </tr>`;
  });

  return `<table>
    <thead><tr>
      <th>Endpoint</th><th>Uptime</th><th>p50</th><th>p95</th><th>p99</th><th>Errors</th><th>TLS Expiry</th>
    </tr></thead>
    <tbody>${rows.join("\n")}</tbody>
  </table>`;
}

function fallbackReport(data: AggregateResult): ReportOutput {
  const table = buildStatsTable(data.endpoints);
  const warnings: string[] = [];

  for (const e of data.endpoints) {
    if (e.uptimePct < 99) {
      warnings.push(`${e.url}: uptime ${e.uptimePct}% (${e.errorCount} errors)`);
    }
    if (e.minTlsExpiryDays !== null && e.minTlsExpiryDays >= 0 && e.minTlsExpiryDays < 30) {
      warnings.push(`${e.url}: TLS cert expires in ${e.minTlsExpiryDays} days`);
    }
    if (e.p95LatencyMs > 1000) {
      warnings.push(`${e.url}: p95 latency ${e.p95LatencyMs}ms`);
    }
  }

  const warningSection = warnings.length > 0
    ? `<h2>Warnings</h2><ul>${warnings.map((w) => `<li>${w}</li>`).join("")}</ul>`
    : "";

  const html = `<!DOCTYPE html>
<html><head><title>Weekly Uptime Report</title>
<style>body{font-family:sans-serif;max-width:900px;margin:0 auto;padding:20px}
table{border-collapse:collapse;width:100%}th,td{border:1px solid #ddd;padding:8px;text-align:left}
th{background:#f5f5f5}</style></head>
<body>
<h1>Weekly Uptime Report</h1>
<p>Period: ${data.periodStart} to ${data.periodEnd}</p>
<p>Overall uptime: <strong>${data.overallUptimePct}%</strong></p>
${table}
${warningSection}
<p><em>Generated by tentacular/uptime-tracker v1.0</em></p>
</body></html>`;

  const summary = `Overall uptime: ${data.overallUptimePct}%. ${data.endpoints.length} endpoints monitored. ${warnings.length} warning(s).`;

  return {
    html,
    summary,
    overallUptimePct: data.overallUptimePct,
    periodStart: data.periodStart,
    periodEnd: data.periodEnd,
  };
}

/** Generate weekly uptime report with LLM narrative and HTML rendering */
export default async function run(ctx: Context, input: unknown): Promise<ReportOutput> {
  const data = input as AggregateResult;

  if (data.endpoints.length === 0) {
    ctx.log.info("No endpoint data to report on");
    return fallbackReport(data);
  }

  const anthropic = ctx.dependency("anthropic");
  if (!anthropic.secret) {
    ctx.log.warn("No anthropic.api_key, generating stats-only report");
    return fallbackReport(data);
  }

  ctx.log.info(`Generating LLM-powered report for ${data.endpoints.length} endpoint(s)`);

  let narrative = "";
  let recommendations: string[] = [];

  try {
    const response = await anthropic.fetch!("/v1/messages", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": anthropic.secret,
        "anthropic-version": "2023-06-01",
      },
      body: JSON.stringify({
        model: "claude-sonnet-4-20250514",
        max_tokens: 2048,
        system: LLM_PROMPT,
        messages: [{
          role: "user",
          content: JSON.stringify({
            period: { start: data.periodStart, end: data.periodEnd },
            overallUptimePct: data.overallUptimePct,
            endpoints: data.endpoints,
          }),
        }],
      }),
    });

    if (!response.ok) {
      ctx.log.warn(`Anthropic API returned ${response.status}, falling back to stats-only`);
      return fallbackReport(data);
    }

    const result = await response.json();
    const text = result?.content?.[0]?.text;
    if (text) {
      const parsed = JSON.parse(text);
      narrative = parsed.narrative ?? "";
      recommendations = parsed.recommendations ?? [];
    }
  } catch (err) {
    ctx.log.warn(`LLM report generation failed: ${err instanceof Error ? err.message : String(err)}`);
    return fallbackReport(data);
  }

  const table = buildStatsTable(data.endpoints);
  const recsHtml = recommendations.length > 0
    ? `<h2>Recommendations</h2><ul>${recommendations.map((r) => `<li>${r}</li>`).join("")}</ul>`
    : "";

  const html = `<!DOCTYPE html>
<html><head><title>Weekly Uptime Report</title>
<style>body{font-family:sans-serif;max-width:900px;margin:0 auto;padding:20px}
table{border-collapse:collapse;width:100%}th,td{border:1px solid #ddd;padding:8px;text-align:left}
th{background:#f5f5f5}</style></head>
<body>
<h1>Weekly Uptime Report</h1>
<p>Period: ${data.periodStart} to ${data.periodEnd}</p>
<p>Overall uptime: <strong>${data.overallUptimePct}%</strong></p>
<h2>Analysis</h2>
<div>${narrative}</div>
<h2>Endpoint Statistics</h2>
${table}
${recsHtml}
<p><em>Generated by tentacular/uptime-tracker v1.0</em></p>
</body></html>`;

  const summary = `Overall uptime: ${data.overallUptimePct}%. ${data.endpoints.length} endpoints. ${recommendations.length} recommendation(s).`;

  ctx.log.info(`Report generated: ${summary}`);

  return {
    html,
    summary,
    overallUptimePct: data.overallUptimePct,
    periodStart: data.periodStart,
    periodEnd: data.periodEnd,
  };
}
