import type { Context } from "tentacular";

interface RepoMetrics {
  repo: string;
  stars: number;
  forks: number;
  openIssues: number;
  openPRs: number;
  recentCommits: number;
  releaseCount: number;
  latestRelease: string;
  topLanguage: string;
  contributorCount: number;
  weeklyCommitTrend: number[];
  velocity: number;
}

interface CompositeMetrics {
  repos: RepoMetrics[];
  rankings: {
    byStars: string[];
    byVelocity: string[];
    byCommits: string[];
    byIssues: string[];
  };
  totals: {
    totalStars: number;
    totalForks: number;
    totalOpenIssues: number;
    totalRecentCommits: number;
  };
  generatedAt: string;
}

interface PublishResult {
  uploaded: boolean;
  reportUrl: string;
}

interface NotifyOutput {
  delivered: boolean;
  status: number;
}

/** Send Slack notification with agent activity report summary */
export default async function run(ctx: Context, input: unknown): Promise<NotifyOutput> {
  const merged = input as { "publish-report": PublishResult; "compute-metrics": CompositeMetrics };
  const publish = merged["publish-report"];
  const metrics = merged["compute-metrics"];

  const slack = ctx.dependency("slack-webhook");
  if (!slack.secret) {
    ctx.log.warn("No slack webhook, skipping notification");
    return { delivered: false, status: 0 };
  }

  // Rankings summary
  const starRanking = metrics.rankings.byStars
    .map((r, i) => `${i + 1}. ${r}`)
    .join("  ");
  const velocityRanking = metrics.rankings.byVelocity
    .map((r, i) => `${i + 1}. ${r}`)
    .join("  ");

  // Per-repo quick stats
  const repoFields = metrics.repos.map((repo) => ({
    type: "mrkdwn",
    text: [
      `*${repo.repo}*`,
      `:star: ${repo.stars.toLocaleString()} stars`,
      `:rocket: ${repo.velocity} velocity`,
      `:busts_in_silhouette: ${repo.contributorCount} contributors`,
      `:git: ${repo.recentCommits} recent commits`,
    ].join("\n"),
  }));

  const blocks: Record<string, unknown>[] = [
    {
      type: "header",
      text: { type: "plain_text", text: "AI Agent Activity Report" },
    },
    {
      type: "section",
      text: {
        type: "mrkdwn",
        text: [
          `:bar_chart: *Rankings Summary*`,
          `*By Stars:* ${starRanking}`,
          `*By Velocity:* ${velocityRanking}`,
        ].join("\n"),
      },
    },
    {
      type: "section",
      fields: repoFields,
    },
    {
      type: "section",
      text: {
        type: "mrkdwn",
        text: [
          `:chart_with_upwards_trend: *Totals*`,
          `Stars: *${metrics.totals.totalStars.toLocaleString()}* | Forks: *${metrics.totals.totalForks.toLocaleString()}* | Issues: *${metrics.totals.totalOpenIssues}* | Commits: *${metrics.totals.totalRecentCommits}*`,
        ].join("\n"),
      },
    },
  ];

  // Report link button
  if (publish.uploaded && publish.reportUrl) {
    blocks.push({
      type: "actions",
      elements: [
        {
          type: "button",
          text: { type: "plain_text", text: "View Full Report" },
          url: publish.reportUrl,
          style: "primary",
        },
      ],
    });
  }

  blocks.push(
    { type: "divider" },
    {
      type: "context",
      elements: [{ type: "mrkdwn", text: `Generated by Tentacular Agent Activity Report | ${new Date().toISOString()}` }],
    },
  );

  ctx.log.info("Sending Slack agent activity notification");

  // slack.secret is a full webhook URL (https://hooks.slack.com/services/...)
  // slack.fetch!() is scoped to the dependency host -- pass path only
  const webhookUrl = new URL(slack.secret);
  const res = await slack.fetch!(webhookUrl.pathname, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ blocks }),
  });

  ctx.log.info(`Slack response: ${res.status}`);

  return { delivered: res.ok, status: res.status };
}
