import type { Context } from "tentacular";
import type { TriageOutput } from "./triage.ts";
import type { CreateIssuesOutput, CreatedIssue } from "./create-issues.ts";

interface AlertResult {
  delivered: boolean;
  alertCount: number;
}

/** Fan-in input: receives both triage data and created issue links */
interface AlertInput {
  "triage": TriageOutput;
  "create-issues": CreateIssuesOutput;
}

/** Post immediate Slack alerts for critical findings with issue links */
export default async function run(ctx: Context, input: unknown): Promise<AlertResult> {
  const data = input as AlertInput;

  // Handle both fan-in and direct input cases
  const triage = data["triage"] ?? data["create-issues"]?.triageOutput;
  const issues = data["create-issues"]?.createdIssues ?? [];

  if (!triage || triage.criticalAction.length === 0) {
    ctx.log.info("No critical alerts to notify");
    return { delivered: true, alertCount: 0 };
  }

  const slack = ctx.dependency("slack-webhook");
  if (!slack.secret) {
    ctx.log.warn("No slack webhook, skipping critical alerts");
    return { delivered: false, alertCount: 0 };
  }

  ctx.log.info(`Sending Slack alerts for ${triage.criticalAction.length} critical vulnerabilities`);

  // Build issue link map
  const issueMap = new Map<string, CreatedIssue>();
  for (const issue of issues) {
    issueMap.set(`${issue.repo}:${issue.alertId}`, issue);
  }

  const alertLines = triage.criticalAction.map((a) => {
    const issue = issueMap.get(`${a.repo}:${a.alertId}`);
    const issueLink = issue ? ` | <${issue.issueUrl}|Issue #${issue.issueNumber}>` : "";
    return `  - :rotating_light: *${a.repo}*: \`${a.identifier}\` (${a.severity}, CVSS: ${a.cvss})${issueLink}\n    ${a.triageReason}`;
  }).join("\n");

  const blocks: Record<string, unknown>[] = [
    {
      type: "header",
      text: { type: "plain_text", text: `CRITICAL: ${triage.criticalAction.length} Vulnerability Alert(s)` },
    },
    {
      type: "section",
      text: {
        type: "mrkdwn",
        text: alertLines,
      },
    },
    {
      type: "section",
      text: {
        type: "mrkdwn",
        text: `*Summary:* ${triage.totalTriaged} total alerts triaged | ${triage.criticalAction.length} critical | ${triage.highTrack.length} high | ${triage.lowLog.length} low`,
      },
    },
    {
      type: "context",
      elements: [
        { type: "mrkdwn", text: `Generated by Tentacular GitHub Vulnerability Triage | ${new Date().toISOString()}` },
      ],
    },
  ];

  const webhookUrl = new URL(slack.secret);
  const res = await slack.fetch!(webhookUrl.pathname, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ blocks }),
  });

  ctx.log.info(`Slack critical alert: ${res.status}`);
  return { delivered: res.ok, alertCount: triage.criticalAction.length };
}
